# Generated by Django 4.2.5 on 2024-03-03 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hordak', '0038_alter_account_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('parent', 'code', 'type')},
        ),
    ]
